# Generated by Django 4.0.4 on 2022-05-18 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0003_goal_is_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.CharField(choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='high', max_length=10),
        ),
    ]
